### ISSUE TITLE
KoreBuild auto-update and version pinning

### ISSUE THREAD

**Issue by mikeharder** [aspnet/KoreBuild#239]
@anurse, @pakrym, and @mikeharder were discussing some changes to KoreBuild designed to improve the reliability of tests and developer builds:

* KoreBuild should automatically update itself if KoreBuild or the CLI has been updated.  Currently, KoreBuild only updates after the ".build" folder is manually deleted.
* KoreBuild should pin the version of ASP.NET packages, so projects will reference `2.0.0-version` rather than `2.0.0-*`.  This has several advantages:
  * Restore should never fail due to new packages being added to the feed
  * Run should never fail due to packages being newer than the installed shared runtime
  * Restore should be much faster
  * We should no longer need a proxy in front of MyGet
* The version of ASP.NET packages should not be updated until we've verified this version of all packages can be downloaded from MyGet

Developer command-line builds (`build.ps1`, `build.sh`) will always install the latest CLI (and shared runtime) ingested by ASP.NET, and pin the package version.

Developer VS builds will use the CLI and package versions installed by the last run of KoreBuild.  While developing in VS, you may fall behind the latest version of CLI and packages, but things should never break.

Some of the CI builds (e.g. UniverseCoherence) may still need to use `2.0.0-*` while building packages.

**Comment by analogrelay** [comment]
For the following:

> KoreBuild should automatically update itself if KoreBuild or the CLI has been updated. Currently, KoreBuild only updates after the ".build" folder is manually deleted.

I couldn't find my code for conditional-GET in `.sh` and `.ps1`, but it wasn't too complicated. In PowerShell you've got `Invoke-WebRequest` which gives you a way to specify Request headers, and the response is an object containing the Response headers. With `curl` there's `-H [HeaderName]: [HeaderValue]` to set request headers and `-D [FileName]` to dump response headers to a file (which can be `grep`ed to get the `ETag`).

I assume, but haven't checked, that both have a timeout mechanism. So the startup flow is

1. Issue a GET with `If-None-Match` using previous Etag (stored in `.build`, if any) for latest KoreBuild zip with a very short timeout
2. If the Get returns a new file, unpack it and replace `.build` with the contents, also store the new `Etag` in `.build`
3. Continue as before

**Comment by Tratcher** [comment]
Is there an opt-out / override? The wildcards have been useful for other things like working on cross-repo changes. E.g. Build repo A, point repo B to repo A's artifacts and build B.

**Comment by kichalla** [comment]
@mikeharder and I were discussing about this scenario. Some options we can use(I like the global override too):
- https://github.com/aspnet/universe#verifying-cross-repo-changes (universe build locally should not use pinning that is being discussed here)
- Removing the $(AspNetCoreVersion) from B which is for the package reference of A and hardcoding to wildcard version (not pretty but should work)

**Comment by analogrelay** [comment]
We could also make it relatively simple to allow the `AspNetCoreVersion` property to be overridden, so it can be provided by either the command line, or a props file.

**Comment by analogrelay** [comment]
The props file would be more useful for Visual Studio work. We could have a `crossrepo.props` file conditionally imported (only if it exists) and `gitignore`d, so that you can just drop it in place and set the version to whatever you want.

**Comment by kichalla** [comment]
Curious to know if there was any idea that has been discussed on how to implement this. Is there going to be a `dependency.props` file checked into Korebuild after every successful Coherence build and from there on any build would have this `dependency.props` file supplied to the repo with the expectation that the individual repos dependency props would get overwritten...also individual repos `dependency.props` file would need to get updated for VS scenarios.

**Comment by analogrelay** [comment]
Why would individual repo `dependencies.props` need to be updated? If KoreBuild supplied the props file and the projects imported it from there (possibly conditionally if we care about the scenario of opening in VS without KoreBuild), then it would be updated in VS as well. `dependencies.props` would be reserved for purely external dependencies (rather than dependencies that we produce as part of our build).

**Comment by kichalla** [comment]
> (possibly conditionally if we care about the scenario of opening in VS without KoreBuild)

Yeah, I actually meant this scenario. If we do not want to initialize (to get the pinned dependency.props) via Korebuild and open VS, was wondering how do we get pinned versions to the repo (sure it need to be the dependency.props that a repo has and could be an imported file but this imported file which is in the repo still needs to be updated for the above VS scenario, right?)

**Comment by analogrelay** [comment]
I think we're already in a situation where KoreBuild is required to run properly in VS. If we did this, I think the way we'd do it is that `dependencies.props` keeps the `2.0.0-*` version, but KoreBuild brings in a props file which overrides it. We can do this by importing the KoreBuild one first and making the `AspNetCoreVersion` property in the repo-local `dependencies.props` conditional on `'$(AspNetCoreversion)' == ''`.

This also leaves open the ability to set a fixed version in the repo-local `dependencies.props` by changing the value and making it unconditional.

**Comment by natemcmaster** [comment]
> KoreBuild should automatically update itself if KoreBuild or the CLI has been updated. Currently, KoreBuild only updates after the ".build" folder is manually deleted.

Why even have a .build folder? Could we have a machine-local cache? `~/.dotnet/korebuild/$version/`?
 This would probably require we implement another idea that we've talked about for a while but never done. See "build korebuild" https://github.com/aspnet/KoreBuild/issues/258. 

We could also update the bootstrapper to take options, such as `--reset-korebuild` or `--korebuild-version`. I know @anurse added some options for KoreBuild2.0, but they never made it into actual repos.

**Comment by pakrym** [comment]
@natemcmaster any problems with files being locked when another build is running? Or just updating in the middle of running build?

**Comment by natemcmaster** [comment]
If we did #258, KoreBuild should never edit/produce files within its own directory. There would be no pre-flight restore anymore so files being locked shouldn't be an issue.

**Comment by natemcmaster** [comment]
Fundamentally, KoreBuild was meant to be a lifecycle for how you build a solution. My gut tells me this is the wrong layer for package reference version pinning. I would be okay with KoreBuild adding a feature to pin the versions, but the data about _which_ versions and _what_ to pin should be config that comes from somewhere else. 

I'm also FYI this could create cyclical build triggers. At the moment, updates to KoreBuild trigger a coherence build. If a coherence build triggers an update to Korebuild, then we may end up in endlessly building. Obviously, fixing it is simple: kill one of the triggers, probably the one at the head of universe build. Use something else, like mirror builds to trigger the run when KoreBuild is updated.

FWIW I think pinning is necessary. Floating has not scaled well.I shared @Tratcher's concern that overriding the pin locally may become messy, and hope we can find a sensible solution that doesn't require too much knowledge of special files, properties, or settings.

**Comment by natemcmaster** [comment]
FYI - we met on this and made some decisions. See https://github.com/aspnet/specs/blob/master/runtime/design-notes/2017-07-22-increasing-build-determinism.md

**Comment by Tratcher** [comment]
So how are cross repo changes supposed to work when there's no longer a nuget.config file or floating package versions?

**Comment by natemcmaster** [comment]
My goal (if I can get time/resources approved for this) is to improve aspnet/Universe to make cross-repo changes easier.

**Comment by pakrym** [comment]
@natemcmaster but how would cross repo changes look after making fixed version change or if you won't get time to improve Universe?

**Comment by natemcmaster** [comment]
It would be about as painful as it is today.

**Comment by pakrym** [comment]
Okay, lets try an example, I do DependencyInjection change and want to test it against MVC, so I add a local feed to MVC repo, put my new DependencyInjection package there and run `.\build`. What would I do in the new world of fixed versions and absence of `NuGet.config`?

**Comment by natemcmaster** [comment]
This doesn't change: https://github.com/aspnet/universe#verifying-cross-repo-changes. 

Part of making this version pinning work will require Universe to have a special way to override the pinned versions of things with the new version it will be building.

**Comment by pakrym** [comment]
So I would need to run universe even if I need to test cross repo change against a single repo?

**Comment by Tratcher** [comment]
Anything that makes cross-repo harder than it already is is a non-starter. I use the same steps @pakrym described. I only run universe at the end for a verification pass, it's too big to use for actual development, especially without incremental builds.

**Comment by natemcmaster** [comment]
Again, my goal (if I can get time/resources approved for this) is to improve aspnet/Universe to make cross-repo changes **easier**.

The exact nature of how a that works is TBD. Build improvements have been de-prioritized until after RTM.

**Comment by kichalla** [comment]
> So I would need to run universe even if I need to test cross repo change against a single repo?

Today I update the Nuget.config of a repo to point to the artifacts folder of the repo that I made a change in. @natemcmaster , I suppose this will still work? @pakrym, how do you do your single cross repo reaction changes today?

From what I have noticed/tried, Universe lifecyle should be different than the one Korebuild does..for example, when you do a regular build.cmd in a repo it clears out the artifacts, but when we want to do a incremental Universe build, this should not happen...

**Comment by pakrym** [comment]
@kichalla I do exactly what you described. My impression is that if all versions would be fixed `restore` would not pickup locally built packages.

**Comment by natemcmaster** [comment]
@pakrym @kichalla The details of how we actually implement what I shared in the meeting notes are TBD. Nothing is changing in the near term. I stand by my previously-expressed reservations on pinning everything via KoreBuild  https://github.com/aspnet/KoreBuild/issues/239#issuecomment-307260590.

**Comment by natemcmaster** [comment]
We met again yesterday to go over the design for how the will work. The current plan is as follows:

 - aspnet/Universe will pin versions when building all repos. Today, aspnet/Universe only pins ASP.NET Core packages. We'll expand this to include external dependencies.
 - When aspnet/Universe completes, it will preserve a list of the versions it pinned in a "lineup file". This lineup file will be published along with the new packages.
 - Individual repos will reference this lineup file. KoreBuild will use it in local builds to pin all PackageReference's.
 - We remove "Version" from all PackageReference. 
 - Devs can override the lineup by adding "Version" to PackageReference, however, this will cause a build warning in Debug, error in Release, and should rarely be checked in.
 - We will try to make improvements to aspnet/Universe to make cross-repo changes less burdensome.

Spec on lineups: https://github.com/aspnet/BuildTools/wiki/%5Bspec%5D-Package-version-lineups

**Work items**

- [ ] Move aspnet/Universe's PinVersions task into KoreBuild
- [x] Add a list of external dependencies to aspnet/Universe
- [ ] Remove Version from PackageReferences and add a reference the lineup. For now, we'll have one lineup package named "Internal.AspNetCore.Coherence.Lineup".
- [ ] Update contributor guidelines so it is clearer that devs must run `build.cmd /t:Restore` before opening VS. We will also add a target to the repos that should detect when this hasn't run yet and display the appropriate error message.

**Comment by smitpatel** [comment]
External dependencies should not be part of it. What is the benefit of doing so?

**Comment by natemcmaster** [comment]
It reduces duplication of dependencies.props across dozens of repos, and makes it easier to update and unify the versions.

**Comment by smitpatel** [comment]
Perhaps you could de-dupe .net core dependencies or some specific ones which are used at multiple place.
Having `Remotion.Linq` which is only used by EF defined here + warning causes more harm than benefit.

**Comment by natemcmaster** [comment]
> Having Remotion.Linq which is only used by EF defined here + warning causes more harm than benefit.

Can you elaborate on your concern? I'm happy to discuss more in person if the EF team isn't convinced they want to participate in this unified approach to managing external dependencies. cc @ajcvickers

**Comment by Eilon** [comment]
We need to have all our dependencies in one place for two benefits:

1. Knowing the list of external (i.e. not our team) dependencies. This is important for being able to ship (e.g. make sure we have RTM versions), it's important for licensing (e.g. make sure we check license compatibility), etc.
2. Ensuring that the same version of a dependency is used everywhere. This is important so we don't bloat things by having more than one version of a dependency, which causes a lot of problems.

We don't update any given external dependency particularly often, so I'm not sure I see why this would be painful.

**Comment by natemcmaster** [comment]
FYI - update.

After a month of experimenting with PackageLineup, we hit some limitations that made it difficult to use across all repos. There were too many edge cases so we decided to switch approaches. Here are some details on the new approach

### PackageReference and the build/dependencies.props file

Floating versions are not allowed. This will cause a build error! PackageReference versions and build-tool versions should be pinned to specific versions.

Each repo will contain a build/dependencies.props file with a section like this:
```xml
  <PropertyGroup Label="Package Versions">
    <InternalAspNetCoreSdkPackageVersion>2.1.0-preview1-15541</InternalAspNetCoreSdkPackageVersion>
    <MicrosoftExtensionsDependencyInjectionPackageVersion>2.1.0-preview1-27430</MicrosoftExtensionsDependencyInjectionPackageVersion>
    <XunitPackageVersion>2.3.0</XunitPackageVersion>
  </PropertyGroup>
```
All PackageReference nodes should use these MSBuild variables.
```xml
<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="$(MicrosoftExtensionsDependencyInjectionPackageVersion)" />
```
### Upgrade automation
This file will be updated automatically about once a week. We are working on a bot/CI config that will upgrade individual repos to new versions about once a week. This is piece is experimental, so this will likely evolve over time.

### Upgrading dependencies 
You don’t have to wait for automation. You can upgrade manually on your own. Of you can executing this command to upgrade the variables in your dependencies.props file:
```
   .\run.ps1 upgrade deps
```
For new projects
You can generate a dependencies.props file from an existing or new project with this command:
```
   .\run.ps1 generate deps
```

For more details, see https://github.com/aspnet/BuildTools/wiki/PackageReference-management

**Comment by natemcmaster** [comment]
This work has been implemented in dev.
